name: codecov

on:
  schedule:
    - cron: 0 0 * * * # at 00:00 AM (UTC) on everyday.
  push:
    branches:
      - ci/**
  workflow_dispatch: {}

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          verbose: true
